# The Docker Config version. Do not change.
version: "3"
services:
  mysqldb:
    image: mysql:8
    # This appears to count as the database name as well
    container_name: speedwaydb
    volumes:
      - speedwaydata:/var/lib/mysql
    networks:
      - speedwaynet
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      # This doesn't seem to work if container_name is set or at all
      MYSQL_DATABASE: speedway_trials
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  api:
    # REPLACE registry/repo:tag with your registry and repo details
    image: lotech/speedway_api:latest
    container_name: speedway_api
    depends_on:
      - mysqldb
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - speedwaynet

volumes:
  speedwaydata:
    driver: local

networks:
  speedwaynet: