# The Docker Config version. Do not change.
version: "3"
services:
  web:
    # REPLACE registry/repo:tag with your registry and repo details
    image: lotech/speedway_api:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
networks:
  webnet: